default: &default
  adapter: <%= ENV['DATABASE_ADAPTER'] || 'mysql2' %>
  database: <%= ENV['DATABASE_NAME'] || 'secure_db' %>
  pool: <%= ENV['DATABASE_POOL'] || '5' %>
  timeout: <%= ENV['DATABASE_TIMEOUT'] || '5000' %>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  username: <%= ENV['DATABASE_USERNAME'] || 'root' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'password' %>
  encoding: <%= ENV['DATABASE_ENCODING'] || 'utf8' %>
  reconnect: true

development:
  <<: *default

production:
  <<: *default
